### ISSUE TITLE
How to start replaykit on another port of adb

### ISSUE THREAD

**Issue by djcm75** [appetizerio/appetizer-toolkit#15]
I would like to run both stf and replaykit, can replaykit run on a separate port ex: 5038
adb start-server -P 5038

**Comment by mingyuan-xia** [comment]
1. replaykit is not a server application. It does not listen on any port. It embeds an ADB client that talks to any ADB server.
2. Most replaykit commands allow you to talk to a non-standard-port ADB server, e.g.,
```
usage: appetizer trace record [-h] [--port PORT] [--host HOST]
                              [--device DEVICE]
                              trace_file
appetizer trace record: error: too few arguments
```
port, host here
3. The problem that replaykit might not work along with STF is because they both use minitouch to control the device. minitouch runs in as a daemon process on the device. Both need to control it.
